CriadoresDeCaes/CriadoresDeCaes/Models/Animais.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CriadoresDeCaes.Models {

   /// <summary>
   /// descrição dos Animais
   /// </summary>
   public class Animais {

      public Animais() {
         ListaFotografias = new HashSet<Fotografias>();
      }

      public int Id { get; set; }

      /// <summary>
      /// nome do cão/cadela
      /// </summary>
      public string Nome { get; set; }

      /// <summary>
      /// data de nascimento
      /// </summary>
      [Required(ErrorMessage = "A {0} é de preenchimento obrigatório")]
      public DateTime DataNascimento { get; set; }

      /// <summary>
      /// Data em que o cão foi comprado
      /// </summary>
      public DateTime? DataCompra { get; set; }
      // o uso do ? transforma o atributo, tornando-o facultativo
      // se já se tiver transferido o Modelo para a BD
      // é preciso atualizar a BD com uma nova Migração

      /// <summary>
      /// Preço de compra do animal
      /// </summary>
      public decimal PrecoCompra { get; set; }

      /// <summary>
      /// Atributo de auxílio à adição do 
      /// preço de compra de um animal
      /// </summary>
      [NotMapped] // esta anotação impede a EF de exportar este atributo para a BD
      [RegularExpression("[0-9]+(.|,)?[0-9]{0,2}",
         ErrorMessage = "Só pode escrever algarismos e, " +
         "se desejar, duas casas decimais no {0}")]
      [Display(Name ="Preço")]
      public string PrecoCompraAux { get; set; }

      /// <summary>
      /// Sexo do cão
      /// F - Fêmea
      /// M - Macho
      /// </summary>
      public string Sexo { get; set; }

      /// <summary>
      /// número de registo no LOP
      /// </summary>
      public string NumLOP { get; set; }

      // *************************************

      /// <summary>
      /// lista das fotografias associadas a um animal
      /// </summary>
      public ICollection<Fotografias> ListaFotografias { get; set; }

      /// <summary>
      /// FK para a Raça do cão/cadela
      /// </summary>
      [ForeignKey(nameof(Raca))]
      [Display(Name = "Raça")]
      public int RacaFK { get; set; }
      public Racas Raca { get; set; }

      /// <summary>
      /// FK para o Criador do cão/cadela
      /// </summary>
      [ForeignKey(nameof(Criador))]
      [Display(Name = "Criador")]
      public int CriadorFK { get; set; }
      public Criadores Criador { get; set; }


   }
}

CriadoresDeCaes/CriadoresDeCaes/Controllers/AnimaisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CriadoresDeCaes.Data;
using CriadoresDeCaes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace CriadoresDeCaes.Controllers {

   [Authorize] // esta anotação irá forçar a
               // autenticação para acesso aos dados
   public class AnimaisController : Controller {

      /// <summary>
      /// este recurso identifica a Base de Dados do projeto
      /// </summary>
      private readonly ApplicationDbContext _bd;

      /// <summary>
      /// este recurso vai proporcionar acesso aos dados dos 
      /// recursos do servidor
      /// </summary>
      private readonly IWebHostEnvironment _webHostEnvironment;

      /// <summary>
      /// dados sobre a pessoa que está a interagir com a aplicação
      /// </summary>
      private readonly UserManager<IdentityUser> _userManager;

      public AnimaisController(
         ApplicationDbContext context,
         IWebHostEnvironment webHostEnvironment,
         UserManager<IdentityUser> userManager
         ) {
         _bd = context;
         _webHostEnvironment = webHostEnvironment;
         _userManager = userManager;
      }

      // GET: Animais
      public async Task<IActionResult> Index() {
         // var auxiliar
         string idDaPessoaAutenticada = _userManager.GetUserId(User);


         /* procurar, na base de dados, a lista dos animal existentes
          * SELECT *
          * FROM Animais a INNER JOIN Criadores c ON a.CriadorFK = c.Id
          *                INNER JOIN Racas r ON a.RacaFK = r.Id
          * WHERE c.UserId = Id da pessoa autenticada
          */
         var listaAnimais = _bd.Animais
                               .Include(a => a.Criador)
                               .Include(a => a.Raca)
                               .Where(a => a.Criador.UserId == idDaPessoaAutenticada)
                               ;

         // invoca a View, enviando uma lista de Animais
         return View(await listaAnimais.ToListAsync());
      }




      // GET: Animais/Details/5
      public async Task<IActionResult> Details(int? id) {

         if (id == null || _bd.Animais == null) {
            return NotFound();
         }

         /* procurar, na base de dados, o animal com ID igual ao parâmetro fornecido
          * SELECT *
          * FROM Animais a INNER JOIN Criadores c ON a.CriadorFK = c.Id
          *                INNER JOIN Racas r ON a.RacaFK = r.Id
          *                INNER JOIN Fotografias f ON f.AnimalFK = a.Id
          * WHERE a.Id = id 
          */
         var animal = await _bd.Animais
                                .Include(a => a.Criador)
                                .Include(a => a.Raca)
                                .Include(a => a.ListaFotografias)
                                .FirstOrDefaultAsync(m => m.Id == id);

         if (animal == null) {
            return NotFound();
         }

         return View(animal);
      }

      // GET: Animais/Create
      /// <summary>
      /// Criar as condições para a View de criação de um animal
      /// ser enviada para o browser
      /// </summary>
      /// <returns></returns>
      public IActionResult Create() {

         // prepara os dados a serem apresentados nas dropdown
         //   ViewData["CriadorFK"] = new SelectList(_bd.Criadores, "Id", "Nome");
         ViewData["RacaFK"] = new SelectList(_bd.Racas, "Id", "Nome");

         // invoca a View
         return View();
      }




      // POST: Animais/Create
      // To protect from overposting attacks, enable the specific properties you want to bind to.
      // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
      /// <summary>
      /// reage aos dados fornecidos pelo Browser
      /// </summary>
      /// <param name="animal">dados do novo animal</param>
      /// <returns></returns>
      [HttpPost]
      [ValidateAntiForgeryToken]
      public async Task<IActionResult> Create([Bind("Nome,DataNascimento,DataCompra,PrecoCompra,PrecoCompraAux,Sexo,NumLOP,RacaFK,CriadorFK")] Animais animal, IFormFile imagemAnimal) {
         /*
          * a anotação Bind serve para autorizar o controller a ler
          * o valor dos atributos que lhe chegam do browser.
          * Se não estiverem identificados, não são lidos
          */

         // vars. auxiliares
         string nomeFoto = "";
         bool existeFoto = false;

         // avaliar se temos condições para tentar adicionar o animal
         // testar se a Raça do animal != 0 e Criador =/= 0
         if (animal.RacaFK == 0) {
            // não foi escolhida uma raça
            ModelState.AddModelError("", "É obrigatório escolher uma Raça.");
         }
         else {
            // se cheguei aqui, escolhi Raça
            // será q escolhi Imagem? Vamos avaliar...

            if (imagemAnimal == null) {
               // o utilizador não fez upload de uma imagem
               // vamos adicionar uma imagem prédefinida ao animal
               animal.ListaFotografias
                     .Add(new Fotografias {
                        Data = DateTime.Now,
                        Local = "NoImage",
                        NomeFicheiro = "noAnimal.jpg"
                     });
            }
            else {
               // há ficheiro. Mas, será que é uma imagem?
               if (imagemAnimal.ContentType != "image/jpeg" &&
                   imagemAnimal.ContentType != "image/png") {
                  //  <=>  ! (imagemAnimal.ContentType == "image/jpeg" || imagemAnimal.ContentType == "image/png")
                  // o ficheiro carregado não é uma imagem
                  // o que fazer?
                  // Vamos fazer o mesmo que quando o utilizador não
                  // fornece uma imagem
                  animal.ListaFotografias
                        .Add(new Fotografias {
                           Data = DateTime.Now,
                           Local = "NoImage",
                           NomeFicheiro = "noAnimal.jpg"
                        });
               }
               else {
                  // há imagem!!!
                  // determinar o nome da imagem
                  Guid g = Guid.NewGuid();
                  nomeFoto = g.ToString();
                  // obter a extensão do ficheiro
                  string extensaoNomeFoto = Path.GetExtension(imagemAnimal.FileName).ToLower();
                  nomeFoto += extensaoNomeFoto;

                  // guardar os dados do ficheiro na BD
                  // para isso, vou associá-los ao 'animal'
                  animal.ListaFotografias
                        .Add(new Fotografias {
                           Data = DateTime.Now,
                           Local = "",
                           NomeFicheiro = nomeFoto
                        });

                  // informar a aplicação que há um ficheiro
                  // (imagem) para guardar no disco rígido
                  existeFoto = true;
               }
            } // if (imagemAnimal == null)
         } // if (animal.RacaFK == 0)


         // atribuir os dados do PrecoCompraAux ao PrecoCompra
         // se não for nulo
         if (!string.IsNullOrEmpty(animal.PrecoCompraAux)) {
            animal.PrecoCompra = Convert.ToDecimal(animal.PrecoCompraAux.Replace('.', ','));
         }

         // ********************************************************************
         // atribuir o ID do Criador 
         // ********************************************************************
         // var auxiliar
         string idDaPessoaAutenticada = _userManager.GetUserId(User);
         int idCriador = await _bd.Criadores
                                  .Where(c => c.UserId == idDaPessoaAutenticada)
                                  .Select(c => c.Id)
                                  .FirstOrDefaultAsync();
         animal.CriadorFK = idCriador;
         // ********************************************************************

         // se os dados recebidos respeitarem o modelo,
         // os dados podem ser adicionados
         if (ModelState.IsValid) {

            try {
               // adicionar os dados à BD
               _bd.Add(animal);
               // COMMIT da ação anterior
               await _bd.SaveChangesAsync();

               // se cheguei aqui, já foram guardados os dados
               // do animal na BD. Já posso guardar a imagem
               // no disco rígido do servidor
               if (existeFoto) {
                  // determinar onde guardar a imagem
                  string nomeLocalizacaoImagem = _webHostEnvironment.WebRootPath;
                  nomeLocalizacaoImagem = Path.Combine(nomeLocalizacaoImagem, "imagens");

                  // e, a pasta onde se pretende guardar a imagem existe?
                  if (!Directory.Exists(nomeLocalizacaoImagem)) {
                     Directory.CreateDirectory(nomeLocalizacaoImagem);
                  }

                  // informar o servidor do nome do ficheiro
                  string nomeDoFicheiro =
                     Path.Combine(nomeLocalizacaoImagem, nomeFoto);

                  // guardar o ficheiro
                  using var stream = new FileStream(nomeDoFicheiro, FileMode.Create);
                  await imagemAnimal.CopyToAsync(stream);
               }
               // devolver o controlo da app para a página de início
               return RedirectToAction(nameof(Index));
            }
            catch (Exception) {
               ModelState.AddModelError("",
                  "Ocorreu um erro com a adição dos dados do(a) " + animal.Nome);
               // throw;
            }

         }

         // preparar estes dados, para quando os dados a introduzir na BD não estão bons

CriadoresDeCaes/CriadoresDeCaes/Controllers/CriadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CriadoresDeCaes.Data;
using CriadoresDeCaes.Models;
using Microsoft.AspNetCore.Authorization;

namespace CriadoresDeCaes.Controllers {
   [Authorize] // esta anotação irá forçar a
               // autenticação para acesso aos dados
   public class CriadoresController : Controller {
      private readonly ApplicationDbContext _context;

      public CriadoresController(ApplicationDbContext context) {
         _context = context;
      }

      // GET: Criadores
      [AllowAnonymous] // anula a ação do [Authorize]
      public async Task<IActionResult> Index() {
         return View(await _context.Criadores.ToListAsync());
      }

      // GET: Criadores/Details/5
      public async Task<IActionResult> Details(int? id) {
         if (id == null || _context.Criadores == null) {
            return NotFound();
         }

         var criadores = await _context.Criadores
             .FirstOrDefaultAsync(m => m.Id == id);
         if (criadores == null) {
            return NotFound();
         }

         return View(criadores);
      }

      // // agora já não preciso deste dois métodos pq
      // // a criação de CRIADORES é feita no registo

      //// GET: Criadores/Create
      //public IActionResult Create()
      //{
      //    return View();
      //}

      //// POST: Criadores/Create
      //// To protect from overposting attacks, enable the specific properties you want to bind to.
      //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
      //[HttpPost]
      //[ValidateAntiForgeryToken]
      //public async Task<IActionResult> Create([Bind("Id,Nome,NomeCriador,Morada,CodPostal,Email,Telemovel")] Criadores criadores)
      //{
      //    if (ModelState.IsValid)
      //    {
      //        _context.Add(criadores);
      //        await _context.SaveChangesAsync();
      //        return RedirectToAction(nameof(Index));
      //    }
      //    return View(criadores);
      //}

      // GET: Criadores/Edit/5
      public async Task<IActionResult> Edit(int? id) {
         if (id == null || _context.Criadores == null) {
            return NotFound();
         }

         var criadores = await _context.Criadores.FindAsync(id);
         if (criadores == null) {
            return NotFound();
         }
         return View(criadores);
      }

      // POST: Criadores/Edit/5
      // To protect from overposting attacks, enable the specific properties you want to bind to.
      // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,NomeCriador,Morada,CodPostal,Email,Telemovel")] Criadores criadores) {
         if (id != criadores.Id) {
            return NotFound();
         }

         if (ModelState.IsValid) {
            try {
               _context.Update(criadores);
               await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException) {
               if (!CriadoresExists(criadores.Id)) {
                  return NotFound();
               }
               else {
                  throw;
               }
            }
            return RedirectToAction(nameof(Index));
         }
         return View(criadores);
      }

      // GET: Criadores/Delete/5
      public async Task<IActionResult> Delete(int? id) {
         if (id == null || _context.Criadores == null) {
            return NotFound();
         }

         var criadores = await _context.Criadores
             .FirstOrDefaultAsync(m => m.Id == id);
         if (criadores == null) {
            return NotFound();
         }

         return View(criadores);
      }

      // POST: Criadores/Delete/5
      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public async Task<IActionResult> DeleteConfirmed(int id) {
         if (_context.Criadores == null) {
            return Problem("Entity set 'ApplicationDbContext.Criadores'  is null.");
         }
         var criadores = await _context.Criadores.FindAsync(id);
         if (criadores != null) {
            _context.Criadores.Remove(criadores);
         }

         await _context.SaveChangesAsync();
         return RedirectToAction(nameof(Index));
      }

      private bool CriadoresExists(int id) {
         return _context.Criadores.Any(e => e.Id == id);
      }
   }
}

CriadoresDeCaes/CriadoresDeCaes/Views/Animais/Create.cshtml
@model CriadoresDeCaes.Models.Animais

@{
   ViewData["Title"] = "Adicionar";
}

<h1>Criar um novo animal</h1>

<hr />

<div class="row">
   <div class="col-md-4">

      @* o parâmetro 'enctype' é fundamental para o formulário
      enviar ficheiros
      *@
      <form asp-action="Create" method="post" enctype="multipart/form-data">

         @* espaço para mostrar as mensagens de erro gerais  *@
         <div asp-validation-summary="ModelOnly" class="text-danger"></div>



         <div class="form-group">
            <label asp-for="Nome" class="control-label"></label>
            <input asp-for="Nome" class="form-control" />
            <span asp-validation-for="Nome" class="text-danger"></span>
         </div>

         <div class="form-group">
            <label asp-for="DataNascimento" class="control-label"></label>
            <input asp-for="DataNascimento" class="form-control" />
            <span asp-validation-for="DataNascimento" class="text-danger"></span>
         </div>

         <div class="form-group">
            <label asp-for="DataCompra" class="control-label"></label>
            <input asp-for="DataCompra" class="form-control" />
            <span asp-validation-for="DataCompra" class="text-danger"></span>
         </div>

         @* adição de um novo atributo para recolher o Preço de Compra
         do animal
         *@
         <div class="form-group">
            <label asp-for="PrecoCompraAux" class="control-label"></label>
            <input asp-for="PrecoCompraAux" class="form-control" />
            <span asp-validation-for="PrecoCompraAux" class="text-danger"></span>
         </div>

         <div class="form-group">
            <label asp-for="Sexo" class="control-label"></label>
            <input asp-for="Sexo" class="form-control" />
            <span asp-validation-for="Sexo" class="text-danger"></span>
         </div>

         <div class="form-group">
            <label asp-for="NumLOP" class="control-label"></label>
            <input asp-for="NumLOP" class="form-control" />
            <span asp-validation-for="NumLOP" class="text-danger"></span>
         </div>

         <div class="form-group">
            <label asp-for="RacaFK" class="control-label"></label>
            @* dropdown *@
            <select asp-for="RacaFK"
                    class="form-control"
                    asp-items="ViewBag.RacaFK">
               <option value="0">-- escolha uma raça, por favor --</option>
            </select>
         </div>
@*
    já não é necessário.
    o Criador está autenticado

         <div class="form-group">
            <label asp-for="CriadorFK" class="control-label"></label>
            <select asp-for="CriadorFK" class="form-control" asp-items="ViewBag.CriadorFK">
               <option value="0">-- escolha um criador, por favor --</option>
            </select>
         </div>*@

         @* recolher a imagem do animal *@
         <div class="form-group">
            <label class="control-label">Fotografia</label>
            <input class="form-control"
                   type="file"
                   accept=".jpg,.jpeg,.png"
                   name="imagemAnimal" />
         </div>

         <br />
         <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
         </div>

      </form>
   </div>
</div>

<div>
   <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
   @{
      await Html.RenderPartialAsync("_ValidationScriptsPartial");
   }
}

CriadoresDeCaes/CriadoresDeCaes/Views/Animais/Delete.cshtml
@model CriadoresDeCaes.Models.Animais

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Animais</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCompra)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCompra)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumLOP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumLOP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Raca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Raca.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Criador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Criador.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CriadoresDeCaes/CriadoresDeCaes/Views/Animais/Details.cshtml
@model CriadoresDeCaes.Models.Animais

@{
   ViewData["Title"] = "Detalhes";
}

<h1>Detalhes do @Model.Nome</h1>

<div>
   <hr />
   <dl class="row">
      <dt class="col-sm-2">
         @Html.DisplayNameFor(model => model.Nome)
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor(model => model.Nome)
      </dd>

      <dt class="col-sm-2">
         @Html.DisplayNameFor(model => model.DataNascimento)
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor(model => model.DataNascimento)
      </dd>

      <dt class="col-sm-2">
         @Html.DisplayNameFor(model => model.DataCompra)
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor(model => model.DataCompra)
      </dd>

      <dt class="col-sm-2">
         @Html.DisplayNameFor(model => model.Sexo)
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor(model => model.Sexo)
      </dd>

      <dt class="col-sm-2">
         @Html.DisplayNameFor(model => model.NumLOP)
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor(model => model.NumLOP)
      </dd>

      <dt class="col-sm-2">
         @Html.DisplayNameFor(model => model.Raca)
      </dt>
      <dd class="col-sm-10">
         @Html.DisplayFor(model => model.Raca.Nome)
      </dd>

      <dt class="col-sm-2">
         @Html.DisplayNameFor(model => model.Criador)
      </dt>
      <dd class="col-sm-10">
         <a asp-action="Details"
            asp-controller="Criadores"
            asp-route-id="@Model?.Criador.Id">
            @Html.DisplayFor(model => model.Criador.Nome)
         </a>
      </dd>
   </dl>

   <h4>Fotografias do @Model.Nome</h4>

   @foreach (var foto in Model.ListaFotografias) {
      <p>
         <img src="~/imagens/@foto.NomeFicheiro"
              alt="fotografia do @Model.Nome"
              title="@Model.Nome no @foto.Local em @foto.Data"
              width="100px" />
      </p>
   }


</div>
<div>
   <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
   <a asp-action="Index">Regressar</a>
</div>

CriadoresDeCaes/CriadoresDeCaes/Views/Animais/Edit.cshtml
@model CriadoresDeCaes.Models.Animais

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Animais</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCompra" class="control-label"></label>
                <input asp-for="DataCompra" class="form-control" />
                <span asp-validation-for="DataCompra" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumLOP" class="control-label"></label>
                <input asp-for="NumLOP" class="form-control" />
                <span asp-validation-for="NumLOP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RacaFK" class="control-label"></label>
                <select asp-for="RacaFK" class="form-control" asp-items="ViewBag.RacaFK"></select>
                <span asp-validation-for="RacaFK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CriadorFK" class="control-label"></label>
                <select asp-for="CriadorFK" class="form-control" asp-items="ViewBag.CriadorFK"></select>
                <span asp-validation-for="CriadorFK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CriadoresDeCaes/CriadoresDeCaes/Views/Animais/Index.cshtml
@model IEnumerable<CriadoresDeCaes.Models.Animais>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Animais</h1>

<p>
    <a asp-action="Create">Adicionar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @* estamos a ler o nome dos atributos *@
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCompra)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumLOP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Raca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Criador)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @* aqui estamos a ler o CONTEÚDO dos registos *@
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNascimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCompra)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumLOP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Raca.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Criador.Nome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>